name: Build and Push Docker image to Docker Hub

on: push

jobs:
  # push_to_registry:this is the Job ID. It is the internal name the system uses 
  #(which is exactly what you would use with the needs: keyword we discussed earlier).
  push_to_registry:
    # This is the human-readable Job Name. It is essentially a description,
    # and it is what actually displays on the GitHub website when you are watching the progress of the workflow.
    name: Push Docker image to Docker Hub 
    runs-on: ubuntu-latest
    environment: packaging
    steps:
      #Just like the job name, this is the human-readable Step Name that shows up in the GitHub UI logs. 
      #If a step needs an internal identifier to be referenced later, it uses the id: keyword instead 
      #(which you can actually see on your Set short SHA step!).
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: |
                wicky2001/docker-automation-sample:${{ env.SHORT_SHA }}
                wicky2001/docker-automation-sample:latest